apiVersion: apps/v1
kind: Deployment
metadata:
  name: gettask
spec: 
  replicas: 2
  selector:
    matchLabels:
      apps: gettask
  template:
    metadata:
      labels:
        apps: gettask
    spec:
      containers:
        - name: getask
          image: appsacrrrrrr.azurecr.io/appsgettask:v1
          ports:
            - containerPort: 8000
          env: 
            - name: CONNECTION_STRING
              value: "Driver={ODBC Driver 18 for SQL Server};Server=tcp:appsserver.database.windows.net,1433;Database=appsdbb;Uid=devops123456;Pwd=devops@123;Encrypt=yes;TrustServerCertificate=no;Connection Timeout=30;"

